# This is a basic workflow to help you get started with Actions

name: GitHubJobSettings

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello message
      run: echo Test-job works!
  deploy-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello message
      run: echo Deploy-job works!
